Import('env', 'arch', 'common', 'messaging')

if arch != "Darwin":
  libusb = Glob("#/.venv/lib/python*/site-packages/libusb/install/lib/libusb-1.0.a")[0]
  libs = [common, messaging, libusb, 'pthread']
  panda = env.Library('panda', ['panda.cc', 'spi.cc', 'usb.cc'])

  env.Program('pandad', ['main.cc', 'pandad.cc', 'panda_safety.cc'], LIBS=[panda] + libs)

  if GetOption('extras'):
    env.Program('tests/test_pandad_canprotocol', ['tests/test_pandad_canprotocol.cc'], LIBS=[panda] + libs)
